# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='packet.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0cpacket.proto\"e\n\x06Packet\x12\x0f\n\x07msgType\x18\x01 \x02(\t\x12\x1c\n\x04smsg\x18\x02 \x02(\x0b\x32\x0e.Packet.subMsg\x1a,\n\x06subMsg\x12\x12\n\nstepNumber\x18\x01 \x02(\x05\x12\x0e\n\x06\x61\x63tMsg\x18\x02 \x02(\t')
)




_PACKET_SUBMSG = _descriptor.Descriptor(
  name='subMsg',
  full_name='Packet.subMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stepNumber', full_name='Packet.subMsg.stepNumber', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actMsg', full_name='Packet.subMsg.actMsg', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=117,
)

_PACKET = _descriptor.Descriptor(
  name='Packet',
  full_name='Packet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgType', full_name='Packet.msgType', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='smsg', full_name='Packet.smsg', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PACKET_SUBMSG, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=117,
)

_PACKET_SUBMSG.containing_type = _PACKET
_PACKET.fields_by_name['smsg'].message_type = _PACKET_SUBMSG
DESCRIPTOR.message_types_by_name['Packet'] = _PACKET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Packet = _reflection.GeneratedProtocolMessageType('Packet', (_message.Message,), dict(

  subMsg = _reflection.GeneratedProtocolMessageType('subMsg', (_message.Message,), dict(
    DESCRIPTOR = _PACKET_SUBMSG,
    __module__ = 'packet_pb2'
    # @@protoc_insertion_point(class_scope:Packet.subMsg)
    ))
  ,
  DESCRIPTOR = _PACKET,
  __module__ = 'packet_pb2'
  # @@protoc_insertion_point(class_scope:Packet)
  ))
_sym_db.RegisterMessage(Packet)
_sym_db.RegisterMessage(Packet.subMsg)


# @@protoc_insertion_point(module_scope)
